#!/bin/bash
#SBATCH -A mxxxx
#SBATCH -C cpu
#SBATCH -q debug
#SBATCH -t 00:30:00
#SBATCH -N 1
#aSBATCH --ntasks-per-node=4
#SBATCH -c 64
##SBATCH --mail-type=all
##SBATCH --mail-user=


# Load openmpi environment
export OMP_NUM_THREADS=1
export SLURM_CPU_BIND="cores"
#export OMP_PLACES=cores
#export OMP_PROC_BIND=spread

#module purge
#module load PrgEnv-gnu/8.3.3

srun ./pic example2d.dat
