#!/bin/bash
#SBATCH --nodes=1
#SBATCH --cpus-per-task=2
#SBATCH --gpus=4
#SBATCH --ntasks-per-gpu=4
#SBATCH --gpus-per-task=1
#SBATCH --gpu-mps
#SBATCH --time=00:10:00
#SBATCH -A pppl
#SBATCH --reservation=test
##SBATCH --mail-type=all
##SBATCH --mail-user=netid@princeton.edu


# Load openmpi environment
export OMP_NUM_THREADS=1
#export OMP_PLACES=cores

module load nvhpc/22.5
module load openmpi/nvhpc-22.5/4.1.3/64

srun ./pic example2d.dat
